b[n++]="Of course this code was stolen, what did you expect?"
b[n++]="Lost in the labyrinth of your own heart, can you still hear the song of the cosmos?"
b[n++]="NO hidden blocks. Studies claim fun has increased by 200%!"
b[n++]="It's going to be a long night."
b[n++]="It's going to be a fun night."
b[n++]="Put forks in microwave (or anything made of metal really)"
b[n++]="OW! Shit!"
b[n++]="I'm supposed to study for exams by the way."
b[n++]="Eek!"
b[n++]="Funding for-by-by-made possible by viewers like you."
b[n++]="BAH! How scary! => https://en.wikipedia.org/wiki/Ghost"
b[n++]="I eat sand"
b[n++]="vivid/stasis - #6 🎧 🟥🟩⬛️⬛️⬛️"
b[n++]="Then God Said, Let There Be Crashes!"
b[n++]="This is a randomly generated title!"
b[n++]="Oh that's AI, AI used to randomize this title"
